const {test}=require("node:test"),assert=require("node:assert/strict");
const {criarServico,normalizarTitulo}=require("../referencia/chamados.cjs");
const dados=require("../fixtures/chamados.json"),ids=itens=>itens.map(item=>item.id);
test("lista inicial ordenada",()=>assert.deepEqual(ids(criarServico(dados).listar()),["CH-001","CH-002","CH-003"]));
test("status isolado",()=>assert.deepEqual(ids(criarServico(dados).listar({status:"aberto"})),["CH-001","CH-003"]));
test("prioridade isolada",()=>assert.deepEqual(ids(criarServico(dados).listar({prioridade:"alta"})),["CH-001"]));
test("filtros combinados por E",()=>assert.deepEqual(ids(criarServico(dados).listar({status:"aberto",prioridade:"alta"})),["CH-001"]));
test("combinação sem resultado",()=>assert.deepEqual(criarServico(dados).listar({status:"concluido",prioridade:"alta"}),[]));
test("status inválido em coleção vazia",()=>assert.throws(()=>criarServico().listar({status:"cancelado"})));
test("prioridade inválida",()=>assert.throws(()=>criarServico(dados).listar({prioridade:"urgente"})));
test("título vazio ou espaços sem mutação",()=>{const s=criarServico(dados);for(const t of ["","   "])assert.throws(()=>s.criar(t));assert.equal(s.listar().length,3);});
test("apara espaços",()=>assert.equal(normalizarTitulo("  Ajustar tela  "),"Ajustar tela"));
test("cria id e valores padrão",()=>assert.deepEqual(criarServico(dados).criar("Novo"),{id:"CH-004",titulo:"Novo",descricao:"",status:"aberto",prioridade:"normal"}));
test("atualiza",()=>{const s=criarServico(dados);s.atualizar("CH-001","concluido","baixa");assert.equal(s.listar({prioridade:"baixa"}).length,1);});
test("atualização inválida é atômica",()=>{const s=criarServico(dados);assert.throws(()=>s.atualizar("CH-001","concluido","urgente"));assert.deepEqual(s.listar(),dados);});
test("id inexistente",()=>assert.throws(()=>criarServico(dados).atualizar("CH-999","aberto","normal")));
test("retornos não expõem estado",()=>{const s=criarServico(dados);s.listar()[0].status="concluido";assert.equal(s.listar()[0].status,"aberto");const novo=s.criar("Novo");novo.titulo="Alterado";assert.equal(s.listar()[3].titulo,"Novo");});
test("defeito de título e solução",()=>{const inicial=require("../laboratorios/estados/titulo-inicial.cjs");assert.equal(inicial("   "),"   ");assert.throws(()=>normalizarTitulo("   "));});
test("defeito OU e solução E",()=>{const bug=require("../laboratorios/estados/filtro-com-bug.cjs");assert.deepEqual(ids(bug(dados,"concluido","alta")),["CH-001","CH-002"]);assert.deepEqual(criarServico(dados).listar({status:"concluido",prioridade:"alta"}),[]);});
